/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

/**
 *
 * @author Kalevus
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnPedido = new javax.swing.JMenuItem();
        mnComprobante = new javax.swing.JMenu();
        mnFactura = new javax.swing.JMenuItem();
        mnBoleta = new javax.swing.JMenuItem();
        mnClientes = new javax.swing.JMenu();
        mnJuridicos = new javax.swing.JMenuItem();
        mnNaturales = new javax.swing.JMenuItem();
        mnTrabajadores = new javax.swing.JMenuItem();
        mnProveedores = new javax.swing.JMenuItem();
        mnProceso = new javax.swing.JMenu();
        mnMantenimiento = new javax.swing.JMenu();
        mnAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Herramientas");

        jMenuItem4.setText("Paquetes");
        jMenu1.add(jMenuItem4);

        mnPedido.setText("Pedido");
        jMenu1.add(mnPedido);

        mnComprobante.setText("Comprobante");

        mnFactura.setText("Factura");
        mnComprobante.add(mnFactura);

        mnBoleta.setText("Boleta");
        mnComprobante.add(mnBoleta);

        jMenu1.add(mnComprobante);

        mnClientes.setText("Clientes");

        mnJuridicos.setText("Juridicos");
        mnClientes.add(mnJuridicos);

        mnNaturales.setText("Naturales");
        mnClientes.add(mnNaturales);

        jMenu1.add(mnClientes);

        mnTrabajadores.setText("Trabajadores");
        jMenu1.add(mnTrabajadores);

        mnProveedores.setText("Proveedores");
        jMenu1.add(mnProveedores);

        jMenuBar1.add(jMenu1);

        mnProceso.setText("Proceso");
        jMenuBar1.add(mnProceso);

        mnMantenimiento.setText("Mantenimiento");
        jMenuBar1.add(mnMantenimiento);

        mnAyuda.setText("Ayuda");
        jMenuBar1.add(mnAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu mnAyuda;
    private javax.swing.JMenuItem mnBoleta;
    private javax.swing.JMenu mnClientes;
    private javax.swing.JMenu mnComprobante;
    private javax.swing.JMenuItem mnFactura;
    private javax.swing.JMenuItem mnJuridicos;
    private javax.swing.JMenu mnMantenimiento;
    private javax.swing.JMenuItem mnNaturales;
    private javax.swing.JMenuItem mnPedido;
    private javax.swing.JMenu mnProceso;
    private javax.swing.JMenuItem mnProveedores;
    private javax.swing.JMenuItem mnTrabajadores;
    // End of variables declaration//GEN-END:variables
}
